#!/usr/bin/env bash
# 002 T19: 22 AC AI-channel auto verification script
#
# Usage:
#   ./scripts/verify_ac.sh                                 # production (https://guess-figure.pages.dev)
#   ./scripts/verify_ac.sh https://staging.example.com     # staging
#   BASE=http://127.0.0.1:8788 ./scripts/verify_ac.sh      # wrangler pages dev local
#
# Chinese handling (Git Bash locale safe):
#   - All JSON payloads with Chinese chars are stored as base64 (pure ASCII source).
#   - Decoded to UTF-8 stdin via `base64 -d`, then curl --data-binary @- reads stdin.
#   - This avoids Git Bash locale corrupting UTF-8 string literals in bash variables.
#   - Encoded JSON content: {"input":"诸葛亮","figure_id":"诸葛亮"} etc.

set -u

BASE="${1:-${BASE:-https://guess-figure.pages.dev}}"
COOKIE_JAR=$(mktemp)
PASS=0; FAIL=0; SKIP=0

# base64 of UTF-8 JSON payloads (generated by scripts/measure_llm_cost.py adjacent script)
# Decode with: echo "$VAR" | base64 -d
B64_ZHUGE_EXACT='eyJpbnB1dCI6IuivuOiRm+S6riIsImZpZ3VyZV9pZCI6IuivuOiRm+S6riJ9'
B64_ZHUGE_TEST='eyJpbnB1dCI6Iua1i+ivlSIsImZpZ3VyZV9pZCI6IuivuOiRm+S6riJ9'
B64_UNIQUE_TEMPLATE='eyJpbnB1dCI6Il9fSU5QVVRfXyIsImZpZ3VyZV9pZCI6IuivuOiRm+S6riJ9'
B64_FINISH_TEMPLATE='eyJnYW1lX2lkIjoiX19HSURfXyIsImZpZ3VyZV9pZCI6IuivuOiRm+S6riIsIndvbiI6ZmFsc2UsInJldmVhbGVkX2NvdW50Ijo3LCJzY29yZSI6MCwiZ2l2ZW5fdXAiOmZhbHNlfQ=='

cleanup() { rm -f "$COOKIE_JAR"; }
trap cleanup EXIT

ok()    { echo "[$1] PASS - $2"; PASS=$((PASS+1)); }
fail()  { echo "[$1] FAIL - $2"; FAIL=$((FAIL+1)); }
skip()  { echo "[$1] SKIP - $2"; SKIP=$((SKIP+1)); }

echo "==========================================================="
echo " 002 verify_ac.sh - target: $BASE"
echo "==========================================================="

# ---------- AC group A: account / cookie ----------

hdrs=$(curl -sI "$BASE/api/daily")
if echo "$hdrs" | grep -qi "set-cookie: gf_uid=" \
   && echo "$hdrs" | grep -qi "HttpOnly" \
   && echo "$hdrs" | grep -qi "Secure" \
   && echo "$hdrs" | grep -qi "SameSite=Lax"; then
  ok AC1 "Set-Cookie has gf_uid + 3 flags"
else
  fail AC1 "Set-Cookie or flag missing"
fi

real_user=$(curl -sc "$COOKIE_JAR" "$BASE/api/me" | grep -oE '"user_id":"[^"]+"' | head -1)
fake_user=$(curl -s -H 'Cookie: gf_uid=00000000-0000-0000-0000-000000000000.tampered' \
  "$BASE/api/me" | grep -oE '"user_id":"[^"]+"' | head -1)
if [ -n "$real_user" ] && [ -n "$fake_user" ] && [ "$real_user" != "$fake_user" ]; then
  ok AC2 "tampered cookie rejected, new user_id issued"
else
  fail AC2 "real=$real_user fake=$fake_user (expected different)"
fi

ma1=$(curl -sI "$BASE/api/daily" | grep -i 'set-cookie' | grep -oE 'Max-Age=[0-9]+' | head -1)
sleep 1
ma2=$(curl -sI "$BASE/api/daily" | grep -i 'set-cookie' | grep -oE 'Max-Age=[0-9]+' | head -1)
if [ "$ma1" = "Max-Age=31536000" ] && [ "$ma2" = "Max-Age=31536000" ]; then
  ok AC3 "Max-Age=31536000 in both requests"
else
  fail AC3 "ma1=$ma1 ma2=$ma2 (expected Max-Age=31536000)"
fi

skip AC4 "secret-missing 500 (production must have it; verify in wrangler local)"

# ---------- AC group B: rate limit / budget ----------

if [ "${SKIP_AC5:-0}" = "1" ]; then
  skip AC5 "SKIP_AC5=1 set (avoid consuming X budget)"
else
  count_429=0
  for i in $(seq 1 70); do
    code=$(echo "$B64_ZHUGE_TEST" | base64 -d | curl -s -o /dev/null -w "%{http_code}" \
      -X POST "$BASE/api/check-answer" \
      -H "Content-Type: application/json" -b "$COOKIE_JAR" \
      --data-binary @-)
    [ "$code" = "429" ] && count_429=$((count_429+1))
  done
  if [ "$count_429" -gt 0 ]; then
    ok AC5 "70 POSTs hit 429 $count_429 times (Rate Limiting triggered)"
  else
    fail AC5 "70 POSTs did not trigger 429 (check dashboard Rule 1 is enabled)"
  fi
fi

skip AC6 "X budget trigger needs LLM_BUDGET_PER_USER=2 (wrangler local)"
skip AC7 "V budget trigger needs LLM_BUDGET_DAILY=2 (same)"
skip AC8 "LLM network error needs mock yunwu (wrangler local intercept fetch)"
skip AC9 "degraded no-consume-clue needs game state (Stage 8 browser DevTools)"
skip AC10 "KV failure strategy unit tested (rate-limit.test.ts 17 cases)"

# ---------- AC group C: cache / performance ----------

# AC11: same input second call -> cached: true
# CF KV has 60s "negative cache" — first GET returns null and runtime caches "null" for 60s.
# Even after PUT, subsequent GET in same edge returns the cached null until 60s expires.
# Workaround: sleep 65s between writes and reads. See https://developers.cloudflare.com/kv/api/read-key-value-pairs/
# Build unique payload: decode template, replace __INPUT__ placeholder (ASCII-safe sed)
unique_input="test_input_$(date +%s%N)"
unique_payload=$(echo "$B64_UNIQUE_TEMPLATE" | base64 -d | sed "s/__INPUT__/$unique_input/")

first=$(printf '%s' "$unique_payload" | curl -s -X POST "$BASE/api/check-answer" -b "$COOKIE_JAR" \
  -H "Content-Type: application/json" --data-binary @-)

echo "  (sleeping 65s for KV global propagation + negative-cache expiry ...)"
sleep 65

second=$(printf '%s' "$unique_payload" | curl -s -X POST "$BASE/api/check-answer" -b "$COOKIE_JAR" \
  -H "Content-Type: application/json" --data-binary @-)
if echo "$second" | grep -q '"cached":true'; then
  ok AC11 "second call has cached: true (cache hit after 65s KV propagation)"
else
  fail AC11 "second response missing cached: true. first=$first second=$second"
fi

skip AC12 "aliases-change cache invalidate, unit tested (llm-cache.test.ts case 2)"

# AC13: cache hit p95 < 200ms (SPEC C9). Run 30 cache-hit, take p95.
latencies=()
for i in $(seq 1 30); do
  t=$(printf '%s' "$unique_payload" | curl -s -o /dev/null -w '%{time_total}' \
    -X POST "$BASE/api/check-answer" -b "$COOKIE_JAR" \
    -H "Content-Type: application/json" --data-binary @-)
  ms=$(awk "BEGIN { printf \"%.0f\", $t * 1000 }")
  latencies+=("$ms")
done
# sort ascending, p95 = 28th of 30 (= ~p93)
p95=$(printf "%s\n" "${latencies[@]}" | sort -n | sed -n '28p')
max_ms=$(printf "%s\n" "${latencies[@]}" | sort -n | tail -1)
if [ -n "$p95" ] && [ "$p95" -lt 200 ]; then
  ok AC13 "30 cache hits p95=${p95}ms < 200ms (max=${max_ms}ms)"
else
  fail AC13 "p95=${p95}ms (expected < 200ms, max=${max_ms}ms)"
fi

# ---------- AC group D: stats persistence ----------

me_json=$(curl -s "$BASE/api/me" -b "$COOKIE_JAR")
if echo "$me_json" | grep -q '"total_games"' \
   && echo "$me_json" | grep -q '"total_wins"' \
   && echo "$me_json" | grep -q '"total_score_30d"' \
   && echo "$me_json" | grep -q '"recent_games"'; then
  ok AC14 "/api/me complete: $me_json"
else
  fail AC14 "/api/me incomplete: $me_json"
fi

# AC15: game/finish idempotent
gid="$(printf '%08x-%04x-%04x-%04x-%012x' \
  $RANDOM$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM$RANDOM 2>/dev/null || echo '12345678-1234-1234-1234-123456789abc')"
finish_payload=$(echo "$B64_FINISH_TEMPLATE" | base64 -d | sed "s/__GID__/$gid/")

r1=$(printf '%s' "$finish_payload" | curl -s -X POST "$BASE/api/game/finish" -b "$COOKIE_JAR" \
  -H "Content-Type: application/json" --data-binary @-)
r2=$(printf '%s' "$finish_payload" | curl -s -X POST "$BASE/api/game/finish" -b "$COOKIE_JAR" \
  -H "Content-Type: application/json" --data-binary @-)
if echo "$r1" | grep -q '"ok":true' && echo "$r2" | grep -q '"ok":true'; then
  ok AC15 "same game_id POSTed twice both ok:true (D1 INSERT OR IGNORE idempotent)"
else
  fail AC15 "r1=$r1 r2=$r2"
fi

me_after=$(curl -s "$BASE/api/me" -b "$COOKIE_JAR")
total=$(echo "$me_after" | grep -oE '"total_games":[0-9]+' | grep -oE '[0-9]+')
if [ -n "$total" ] && [ "$total" -ge 1 ]; then
  ok AC16 "/api/me total_games=$total (AC15 write reflected)"
else
  fail AC16 "total_games not +1: $me_after"
fi

if pnpm exec wrangler d1 execute guess-figure-db --local \
   --command "PRAGMA table_info(users)" 2>/dev/null \
   | grep -q '"name": *"email"' && \
   pnpm exec wrangler d1 execute guess-figure-db --local \
   --command "PRAGMA table_info(users)" 2>/dev/null \
   | grep -q '"name": *"merged_from_user_id"'; then
  ok AC17 "local D1 users has email + merged_from_user_id fields"
else
  fail AC17 "users table incomplete (run wrangler d1 migrations apply --local first)"
fi

# ---------- AC group E: UX / loading (manual) ----------

skip AC18 "loading 200ms phase 1 - DevTools Slow 3G manual"
skip AC19 "loading 5s phase 2 - manual"
skip AC20 "cache-hit 'instant' feel (AC13 already verified < 200ms)"

# ---------- AC group F: backward compat ----------

# AC21: no cookie POST -> 200 + new Set-Cookie. Use -D - to dump headers.
fresh_hdrs=$(echo "$B64_ZHUGE_EXACT" | base64 -d | curl -s -D - -o /dev/null \
  -X POST "$BASE/api/check-answer" \
  -H "Content-Type: application/json" --data-binary @-)
if echo "$fresh_hdrs" | grep -qi '^HTTP.*200' && echo "$fresh_hdrs" | grep -qi 'set-cookie: gf_uid='; then
  ok AC21 "no-cookie POST -> 200 + new cookie issued"
else
  fail AC21 "fresh hdrs: $fresh_hdrs"
fi

if pnpm test > /dev/null 2>&1; then
  ok AC22 "pnpm test passed (incl. 001 behavior tests)"
else
  fail AC22 "pnpm test failed"
fi

# ---------- summary ----------

echo "==========================================================="
TOTAL=$((PASS + FAIL + SKIP))
echo " Summary: $PASS / $TOTAL PASS (FAIL=$FAIL, SKIP=$SKIP)"
echo "==========================================================="

if [ "$FAIL" -eq 0 ] && [ "$PASS" -ge 12 ]; then
  echo "Stage 7 ready (12+ AC auto PASS, 0 FAIL)"
  exit 0
else
  echo "FAILs present or PASS < 12, fix and rerun"
  exit 1
fi
